"""Explicit human-review ledger. This script serializes judgements; it does not infer deep-reading completion."""
import json,subprocess
from pathlib import Path
root=Path(__import__('sys').argv[1]);here=Path(__file__).resolve().parent
inv=json.loads((here/'source-inventory.json').read_text());files={x['gitPath']:x for x in inv['files']};sha=inv['baselineSHA'];assert sha=='fb0e1e62841106c533e4edd1d7e60327dc4315b4','Curated judgements require explicit re-review on a new baseline'
out={'baselineSHA':sha,'reviewPolicy':'FULL_FILE_DEEP_REVIEW means all file sections read in this round; targeted/reused/AST is separate. Review statements are author evidence, not mechanically proved understanding.','files':[],'traces':[],'states':[],'boundaries':[],'gaps':[]}
def evidence(path,start=1,end=None):return {'path':path,'lineStart':start,'lineEnd':min(end or len((root/path).read_text().splitlines()),len((root/path).read_text().splitlines())),'blobSHA':files[path]['blobSHA'],'commitSHA':sha}
def reviewed(path,note,full=False,start=1,end=None):out['files'].append({'path':path,'level':'FULL_FILE_DEEP_REVIEW' if full else 'TARGETED_READ','evidence':[evidence(path,start,end)],'judgement':note,'remaining':'External/configuration/quality proof not implied' if full else 'Other file sections remain pending'})
# The small complete units were read with all their validation and exceptional branches.
fulls={
'packages/database/src/index.ts':'Windows localhost normalization; pool creation/lifetime is host-owned. Not a semantic intelligence facility.',
'packages/cognition/src/capability-observation.ts':'SUCCESS preserves nonempty <=16000 characters; other statuses forbid content. Tool identity opaque.',
'apps/server/src/mcp-read-text-observation.ts':'Revalidates binding, joins text blocks; malformed/empty/over-limit success becomes ERROR without body or reason.',
'apps/server/src/routes/websocket.ts':'Trace registry versus dashboard wildcard stream, query coercion, close unsubscribe, deprecated /v1/events closure. Actual socket fixture tests no-active-trace suppression and false-string widening.',
'apps/server/src/routes/security.ts':'Dashboard dev-token/loopback helpers are explicit route guards, not global authentication.',
'apps/server/src/routes/events.ts':'Recent-event dashboard reads are management consumers.',
'apps/server/src/routes/debug.ts':'Development debug route differs from production event route.',
'packages/event-bus/src/index.ts':'Wildcard subscribers and catch/log handler errors; publication completion does not certify all subscriber effects. Other subscribers continue.',
'packages/character-harness/src/assembly-v2d.ts':'Prefix-only budget closure drops all later sections; counts cognition semantic strings. Does not re-rank or summarize.',
'packages/providers/src/local/DotsTTSProvider.ts':'Exactly one whole-text HTTP request, input WAV/language check, 400 -> provider error unknown effect, cancellation and readiness.',
'services/dots-tts/server.py':'Actual handler length cap, 2000-character service bound, locks, idle hibernation, late cancellation discards generated audio, explicit local-only startup.',
'services/memory-mem0/src/yuvi_mem0/config.py':'MEM0 inference/provider routing, configured model/temperature; not simply assumed default rules.',
'services/memory-mem0/src/yuvi_mem0/noop_llm.py':'Explicit no-inference compatibility adapter; availability alone is not semantic extraction.',
'services/memory-mem0/src/yuvi_mem0/__main__.py':'Module entry calls uvicorn with config; no hidden periodic individual-life process.',
'apps/web/src/companion-embodied-behavior-diagnostics.ts':'Bounded DEV-only browser diagnostics; intentional debug consumer, no production self-state claim.',
'packages/memory/migrations/009_finalized_ingestion_work_discovery_v1.sql':'Due-work index covers pending/retry/expired/reconcile; no semantic state write or autonomous job executor.'}
for p,n in fulls.items():reviewed(p,n,True)
for p,a,b,n in [
('apps/server/src/read-text-effect.ts',1,120,'Real regular-file adapter accepts <=64000 bytes. Durable grant/dispatcher inspected only in prefix; recovery remains open.'),
('services/local-stt/server.py',330,442,'Actual per-span ASR and mixed-voice matching policy; invalid audio decode and span recognition probed. Initialization/complete HTTP failure matrix pending.'),
('services/local-stt/speaker_store.py',1,65,'Acoustic template persistence is explicitly not Person/P8; remainder native governance open.'),
('apps/server/src/server.ts',75,245,'Plugin lifecycle hooks and all route registration; characterComposition suppresses management endpoints; default no plugin discovery/grants.'),
('apps/server/src/context.ts',250,300,'EventBus dashboard consumer and backend selection, repository/lifecycle construction.'),
('apps/server/src/context.ts',515,645,'Person used for runtime scope, Character/Cognition/read-text wiring, whole speech passes same text; no semantic Profile read here.'),
('apps/server/src/context.ts',780,808,'Lifecycle shutdown and exported ScopePeopleModelReader construction; exposure is not consumption.'),
('apps/server/src/routes/message.ts',90,220,'Receipt before Runtime, normalized identity and options, explicit controlAuthority, accounted target, null silence response.'),
('apps/server/src/routes/message.ts',270,306,'Both HTTP aliases and default memory option normalization.'),
('apps/server/src/routes/message-stream.ts',1,125,'SSE transport shares schema/options/receipt; continuation/cancel/recovery needs further deep review.'),
('apps/server/src/routes/media.ts',55,86,'TTS schema lacks service-specific max; image/multimodal schema explicit.'),
('apps/server/src/routes/media.ts',610,702,'Receipt, disconnect boundary, whole/segmented media seal and unchanged text provider call.'),
('apps/server/src/tts-receipt-admission.ts',1,95,'Raw TTS text is NOT_RETAINED/nonselectable; metadata summary is retained; intentional privacy state boundary.'),
('apps/server/src/tts-receipt-admission.ts',130,168,'Unresolved principal/source acknowledged; appendWithHostAuthority fails closed; no sourceDedup invented.'),
('apps/server/src/services/dashboard.ts',1,82,'Recursive key redaction leaves ordinary text/content intact; management consumer only.'),
('packages/core/src/runtime-orchestrator.ts',1200,1245,'A4 Profile explicitly NOT_USED; P8 owner sources differ; not proof every possible host omits Profile.'),
('packages/core/src/runtime-orchestrator.ts',4655,4715,'Whole speech includes unchanged reply.payload.content; configured media wrapper does not chunk here.'),
('packages/memory/src/profile-lifecycle.ts',748,810,'Reader facade delegates lifecycle. Typed reference or instantiated facade does not prove product consumer.'),
('apps/desktop/src-tauri/src/config/env_export.rs',1,135,'Native managed/external settings export, runtime endpoint and memory config mapping.'),
('apps/desktop/src-tauri/src/config/env_export.rs',160,290,'Secrets for owned consumers; native sidecar settings forwarding. Actual Windows/macOS execution remains untested.'),
('apps/desktop/src-tauri/src/lib.rs',275,335,'Tauri command list and app lifecycle event registration, explicit command host.'),
('apps/desktop/src-tauri/src/supervisor.rs',1735,1754,'Tree-sitter grammar ERROR on HTTP response split/let syntax. No Rust compiler available; parsing incompleteness retained.'),
('packages/desktop-supervisor/src/types.ts',1,105,'Ownership/instance/token and STT lease states are runtime safeguards, not cognition state.'),
('packages/config/src/index.ts',1,120,'Selectors/defaults source; capability selectable does not imply reachable from Chat.'),
('packages/core/src/index.ts',1,138,'Barrel reexports include proactive/interaction/effects; exports are not entry traces.'),
('packages/effects/src/model.ts',1,80,'Static host-owned effect contracts and necessary correct execution boundary.'),
('packages/journal/src/index.ts',1,105,'Repository interface and host authority draft; SQL transaction implementation remains deep-review pending.'),
('packages/prompt-builder/src/canonical-context.ts',1,130,'Shared slots, stable/volatile partition and assembly shape; classification alone does not replace model serialization.'),
('packages/providers/src/accounting.ts',1,100,'AsyncLocal work/task scope and logical task descriptor; all network leaves/fallback paths not reviewed.'),
('scripts/desktop-package/build-linux-mem0.mjs',1,65,'PyInstaller manifest & interpreter/version validation; not executing release build.'),
('services/local-stt/packaging/runtime_notices.py',1,65,'Actual build interpreter notices; hashes native origins, Debian boundary, unknown inputs fail release; remainder attribution logic pending.'),
('packages/character-abi/src/v2d.ts',1,95,'Typed ABI constraints and sections; cannot infer semantic value from contract validity.'),
('packages/host-environment/src/index.ts',1,80,'Environment host includes guarded command/storage paths; large file remains open.'),
('packages/protocol/src/index.ts',1,80,'Protocol is schema and shared types; deep review of full registry remains open.'),
('packages/p8/src/correction.ts',1,80,'Correction descriptors/evidence predicates; natural-language reachability requires Runtime trace, not an export.')]:reviewed(p,n,False,a,b)
for p,n in [('apps/server/src/product-person-command-effects.ts','CREATE/UPDATE and voice binding exact target/revision schemas; cross-owner fenced native updates require actual DB proof'),('packages/effects/src/dispatch-store.ts','Store interface and attempt row decoder: fences/leases/control states; low visibility does not mean unused reliability facility'),('scripts/desktop-package/installer-smoke.mjs','Isolated real installer/supervisor smoke, strips credentials and PATH tools; release validation is part of build scope despite not ordinary runtime'),('apps/web/src/companion-page.tsx','Companion owns renderer/audio queue and presentation acknowledgments; HTTP report chain catches errors without diagnostic, complete retry/reconciliation remains OPEN')]:reviewed(p,n,False,1,85)
out['gaps'].append({'id':'OPEN-PRESENTATION-REPORT','kind':'EXTERNAL_CALLBACK_RECOVERY_GAP','path':'apps/web/src/companion-page.tsx','status':'OPEN_GAP','reason':'Lines 78-85 catch presentation outcome API errors with undefined; full client/server retry/reconciliation not traced, so cannot yet declare outward effect forgotten or intelligent behavior harmed.'})
reviewed('apps/server/src/character-runtime.ts','Actual factory, initial/reentry gate, cognition handoff and protection; all symbols verified; remainder body/visual/retry functions not full-file reviewed',False,139,262)
# A: independently assembled entry traces. Each records cause/input/normalization/authority/terminal/error.
def trace(id,entry,steps,stateids,boundids,activation,authority,terminal,fail):
 out['traces'].append({'id':id,'entryPaths':entry,'activation':activation,'inputProvider':'External client/host/scheduler as stated in activation','steps':[{'path':p,'function':f,'condition':c} for p,f,c in steps],'stateIDs':stateids,'boundaryIDs':boundids,'normalization':'At schema, receipt and Runtime steps; see linked field-boundary records','authority':authority,'terminalConsumer':terminal,'failureCancellationRestart':fail,'status':'TARGETED_CHAIN_WITH_OPEN_BRANCHES','evidenceBoundary':'Source/recording probes do not prove deployed configuration or model quality'})
trace('A-HTTP',['apps/server/src/routes/message.ts'],[('apps/server/src/routes/message.ts','handleMessage','valid MessageRequestSchema -> identity/options -> host receipt'),('apps/server/src/context.ts','new RuntimeOrchestrator','configured production ports'),('packages/core/src/runtime-orchestrator.ts','handleUserMessage/handleUserTurn/executeCharacterTurn','prepare context -> Character -> Cognition if admitted'),('apps/server/src/character-runtime.ts','createServerCharacterPort','provider-facing control and expression calls'),('packages/core/src/runtime-orchestrator.ts','persistUserMessage/persistCompletedAssistantReply','conversation and outward reply')],['S-Conversation','S-Journal','S-Context','S-P8','S-Memory'],['C-Receipt','C-Context','C-Control','C-Publication'],'POST /message or /v1/messages; valid body and ready database/Journal','Transport asserted identity not authenticated principal; LOCAL_EXPLICIT_CONTROLLER; host grants separate','HTTP accounted reply or intentional null silence','Admission failure before Runtime; cancellation/accounted output branches partial; restart workers separate')
trace('A-SSE',['apps/server/src/routes/message-stream.ts'],[('apps/server/src/routes/message-stream.ts','registerMessageStreamRoutes','schema/receipt then stream'),('packages/core/src/runtime-orchestrator.ts','streamUserMessage','shared prepared context and publication')],['S-Conversation','S-Journal','S-Context'],['C-Receipt','C-Publication'],'POST stream endpoint','Shared identity/options; disconnect tracking','SSE event frames; not dashboard stream','Deep cancellation/component-recovery matrix pending')
trace('A-WS',['apps/server/src/routes/websocket.ts'],[('apps/server/src/routes/websocket.ts','registerWebSocketRoutes','query then activeTrace or dashboard wildcard subscriber'),('packages/event-bus/src/index.ts','publish/subscribe','await matched handlers; subscriber failures caught'),('apps/server/src/services/dashboard.ts','redactValue','key-based redaction'),('apps/server/src/routes/websocket.ts','sendAccounted','target-liveness gate')],['S-Events','S-Dashboard','S-Publication'],['C-WSQuery','C-Dashboard'],'WS /ws; /v1/events explicitly closes','No global authentication demonstrated in inspected server hook; target predicate is dashboard||activeTrace','Socket receives selected diagnostic or reply frame','close unsubscribes; outward store/accounting not exercised by fixture')
trace('A-ReadText',['apps/server/src/cognition-production.ts'],[('apps/server/src/cognition-production.ts','executeProductionCognition','NEED_COGNITION and host runtimeAuthorizedPath'),('apps/server/src/mcp-read-text-capability.ts','executeServerMcpReadTextCapability','admission/binding/current grant'),('apps/server/src/read-text-effect.ts','readAuthorizedLocalText','bounded regular-file decode'),('apps/server/src/mcp-read-text-observation.ts','createServerMcpReadTextObservation','normalize outcome'),('apps/server/src/cognition-production.ts','executeProductionCognition','observation feeds next Reasoning round')],['S-Capability','S-ToolResult','S-Observation','S-Effect'],['C-FileObservation','C-CapabilityRequest'],'Admitted model capability request + host-authorized path, not arbitrary conversational path','Host path/operation freshness; no model self-grant','Next Reasoning input; only transient read result','Cancel before read => no result; 16k+ result => ERROR; durable recovery not probed')
trace('A-TTS',['apps/server/src/routes/media.ts'],[('apps/server/src/routes/media.ts','registerMediaRoutes','valid request -> receipt -> sealWhole/sealSegment'),('packages/providers/src/local/DotsTTSProvider.ts','synthesizeSpeech','one HTTP unchanged text body'),('services/dots-tts/server.py','do_POST/synthesize','16KB HTTP body / 2000 stripped chars -> audio'),('apps/server/src/routes/media.ts','registerMediaRoutes','audio response/publication')],['S-TTSReceipt','S-Media','S-Effect'],['C-TTSReceipt','C-TTSWire'],'POST /v1/tts or Runtime whole-speech with local dots selected','Receipt and media-effect control; owns speech request; fixture bypasses durable seal only','WAV/audio payload or mapped ProviderError','Caller abort does not certify remote noninvocation; cancellation discards late result; oversized text 400')
trace('A-STT',['services/local-stt/server.py','apps/server/src/routes/media.ts'],[('services/local-stt/server.py','do_POST/handle_transcribe','audio decode -> whole ASR -> timed span ASR'),('packages/providers/src/local/LocalSTTProvider.ts','transcribeAudio','provider adaptation (static candidate, exhaustive path pending)'),('apps/server/src/routes/media.ts','admitFinalizedSpeech','reservation and journal evidence'),('packages/core/src/runtime-orchestrator.ts','commitSpeechTurn/handleUserMessage','finalized speech text -> conversation/model')],['S-Speech','S-VoiceProfile','S-Journal','S-Conversation'],['C-STTSpans','C-SpeechContext'],'Local STT selected + audio; optional diarize/identify','Voice profile is acoustic template, not person identity; host capture fence/receipt','Timed result, text turn and review surface; model sees transcript; complete cluster projection not proved by sidecar test','Bad WAV fails decode; full media route timeout/cross-process cancellation pending')
trace('A-Native',['apps/desktop/src-tauri/src/lib.rs','apps/desktop/src-tauri/src/main.rs'],[('apps/desktop/src-tauri/src/lib.rs','run','registered Tauri commands and app lifecycle'),('apps/desktop/src-tauri/src/config/env_export.rs','public_env_overrides/secret_env_overrides/combined_env_for_supervisor','managed settings/secrets to env'),('apps/desktop/src-tauri/src/supervisor.rs','bootstrap_supervisor','host service ownership/health/restart')],['S-Supervisor','S-Settings'],['C-NativeEnv'],'Desktop app launch/explicit invoke/window lifecycle','Managed/external ownership and host secret boundaries','Owned server/sidecars, UI diagnostics','Platform cfg/process kill/release binaries not executed; Rust grammar error remains')
trace('A-Mem0',['services/memory-mem0/src/yuvi_mem0/__main__.py'],[('services/memory-mem0/src/yuvi_mem0/__main__.py','main','uvicorn entry'),('services/memory-mem0/src/yuvi_mem0/app.py','add_memory/submit_idempotent_memory/search_memories/list_memories','configured memory operations'),('services/memory-mem0/src/yuvi_mem0/config.py','get_settings','inference/provider construction')],['S-Mem0','S-Profile'],['C-Mem0'],'Mem0 backend selected, sidecar ready, grounded finalized evidence','Scope/lineage and no invented default subject','Search records can enter Runtime; bounded snapshot supports profile source','Actual sidecar DB/model ingestion not run; exception/compatibility branches pending')
trace('A-Dashboard',['apps/server/src/routes/events.ts','apps/server/src/routes/debug.ts'],[('apps/server/src/context.ts','createAppContext','records diagnostics'),('apps/server/src/services/dashboard.ts','recordEvent/listRecentEvents','bounded 200 events redaction'),('apps/server/src/routes/events.ts','registerEventRoutes','management read')],['S-Events','S-Dashboard'],['C-Dashboard'],'Management HTTP/diagnostic client','Per-route guards differ; no semantic scope by default dashboard listing','Dashboard, not future model memory','Bounded list intentionally drops older diagnostics')
trace('A-Proactive',['apps/server/src/routes/proactive-turn-stream.ts','apps/server/src/context.ts'],[('apps/server/src/context.ts','startProactiveScheduler','boot config/default session/consent eligibility'),('packages/core/src/runtime-orchestrator.ts','runScheduledProactiveAttempt','decision provider score, Character proposal and admission'),('apps/server/src/routes/proactive-turn-stream.ts','registerProactiveTurnStreamRoutes','local consent projection and idempotent external turn stream')],['S-Proactive','S-Context','S-Publication'],['C-Control','C-Publication'],'Authorized consent + due eligibility or explicit proactive request','Local dashboard access guard/consent revision, no model self-consent','Admitted reply or NO_OP/backoff','All timer/engagement combinations pending; old default-session probe reused')
trace('A-Worker',['apps/server/src/server.ts'],[('apps/server/src/server.ts','buildServer','starts profile lifecycle/maintenance/ingestion/readTextEffects workers'),('packages/memory/src/profile-lifecycle.ts','ProfileLifecycleCoordinator','due lease/source lineage verification'),('packages/memory/src/memory-ingestion-coordinator.ts','MemoryIngestionCoordinator','configured coordinator worker from @companion/memory; SQL integration pending')],['S-Profile','S-Memory','S-Effect','S-Dream'],['C-Mem0'],'Server configured DB/source and worker startup','Owner leases/fences and grounded evidence','Persistent terminal/retry/reconcile state; conditional memory source','No database-backed recovery run; not every worker declares semantic consumer')
trace('A-Plugins',['apps/server/src/server.ts','apps/server/src/plugin-lifecycle.ts'],[('apps/server/src/server.ts','buildServer','discover->load->start; default discovery [] and grants []'),('apps/server/src/plugin-lifecycle.ts','snapshotExecutableCapabilities/invokeExecutableCapability','host-issued handles authorize registered implementation'),('apps/server/src/context.ts','executeProductionCognition','snapshot/invoke surface')],['S-Capability','S-Effect'],['C-CapabilityRequest'],'Host-injected plugin source, compatible manifest and host grants','Declarations cannot grant authority; callback registry requires explicit host composition','Admitted capability observation/reasoning, or rejection/unavailable','Loader/start timeout/late callbacks/external plugin processes not exhaustively investigated')
trace('A-Vision',['apps/server/src/routes/media.ts'],[('apps/server/src/routes/media.ts','registerMediaRoutes','image input -> vision receipt -> selected provider analyzeImage'),('apps/server/src/character-runtime.ts','generateAcceptedCharacterProposal','optional single visual evidence cycle with requestVisualEvidence'),('packages/core/src/runtime-orchestrator.ts','executeCharacterTurn','analysis text enters current model context')],['S-Vision','S-Journal','S-Context'],['C-Receipt','C-Control'],'Image/media request or host-enabled screen-evidence request','Host capture/receipt and provider grants; raw image not text memory','Current untrusted observation text or unavailable evidence','Real hardware and vision provider untested; exhaustive repeated-observation matrix pending')
trace('A-Browser',['apps/web/src/main.tsx'],[('apps/web/src/main.tsx','renderSurface','Vite index loads browser/webview UI'),('apps/web/src/companion-embodied-behavior-diagnostics.ts','recordCompanionEmbodiedBehaviorDiagnostic','DEV-only presentation diagnostics')],['S-Settings','S-Media','S-Publication'],['C-Publication'],'Browser or Tauri webview boot','Selected server endpoint; native bridge in desktop mode','Rendered chat/audio/Live2D/management controls','Full UI event/capture/playback timing not reviewed; import graph is only reachability candidate')
ws=next(t for t in out['traces'] if t['id']=='A-WS')
ws['steps'].extend([{'path':'apps/server/src/routes/websocket.ts','function':'registerWebSocketRoutes','condition':'INBOUND: parse RuntimeEvent/UserMessageEvent, admit host receipt, attach sourceJournalRef; invalid packet may remove existing trace'},{'path':'packages/core/src/runtime-orchestrator.ts','function':'handleUserMessage','condition':'INBOUND valid text: actual Runtime call; its emitted reply returns through already-listed subscription'}])
ws['stateIDs'].extend(['S-Journal','S-Conversation','S-Context','S-WSTrace']);ws['boundaryIDs'].extend(['C-Receipt','C-Context','C-Control','C-Publication','C-WSTrace'])
ws['activation']='WS /ws connection: incoming user.message and outgoing diagnostics/reply branches; /v1/events closes'
ws['stepOrder']='Listed nodes include input/output callbacks; not a single synchronous linear stack'
# B: important artefacts, their actual semantic consumers and open wiring classes.
def state(id,name,producers,consumers,kind,model,action,update,notes,dynamic='PARTIAL_BOUNDARY_REVIEW'):
 out['states'].append({'id':id,'name':name,'producers':producers,'consumers':consumers,'consumptionKind':kind,'readsEnterModel':model,'affectsAction':action,'feedsStateUpdate':update,'consumerStatus':'IDENTIFIED_WITH_CONDITIONS' if consumers else 'UNRESOLVED','dynamicAuditStatus':dynamic,'questions':notes,'traceIDs':[t['id'] for t in out['traces'] if id in t['stateIDs']]})
state('S-Journal','Journal envelope/retained selectable text',['Host receipt admission appendWithHostAuthority; PostgreSQL Journal'],['Conversation admission; finalized ingestion; effect causal reader'],'AUTHORITY/LINEAGE_AND_ELIGIBLE_SOURCE','Indirect selectable text; raw media explicitly not retained',True,True,['Principal UNKNOWN is not authenticated Person; complete SQL recovery pending'])
state('S-Conversation','User/assistant history and reply components',['Runtime conversation writes; provisional/terminal reply'],['Runtime prepareTurn/build context; history HTTP/UI'],'CONTEXT_AND_DISPLAY',True,False,True,['Stored faithful row does not imply full-length model projection; cancellation/component completion gaps'])
state('S-Context','Canonical shared/stable/volatile context',['Runtime + P8/Memory/PromptBuilder projections'],['Character provider rendering; Cognition canonical context'],'MODEL_INPUT',True,True,False,['Prefix budget means semantic slots may be omitted'])
state('S-P8','Authored identity and evidence-backed corrections',['Host authored composition; correction store; evidence adapter'],['Character ABI identity/persona/relationship projection'],'MODEL_INPUT_WITH_AUTHORITY',True,True,True,['An empty meaning candidate is not relationship learning; natural-language correction path partly reused'])
state('S-Memory','Legacy L0/L1/L2 and retrieval context',['Grounded user candidate extraction; recent episode/Dream writer conditional'],['Runtime buildMemoryVNextContext/search and Character memory evidence'],'MODEL_CONTEXT',True,False,True,['All negative/correction/retention paths not closed; backend selection matters'])
state('S-Mem0','Mem0 inferred scoped records',['Python infer path + finalized ingestion coordinator'],['Runtime Mem0 provider search; source snapshot/Profile lifecycle'],'MODEL_CONTEXT_AND_SOURCE',True,False,True,['Previous positive fixture verifies search consumed; actual LLM writing/quality needs credentials'])
state('S-Profile','Synthesized Profile snapshot/lifecycle materialization',['LocalProfileProvider; ProfileLifecycleCoordinator worker'],['Lifecycle verification/status; exported ScopePeopleModelReader facade'],'STORAGE/VALIDATION; A4_EXPLICIT_NOT_USED','A4 NO; other hosts UNRESOLVED','UNRESOLVED',True,['Inspected A4 explicitly NOT_USED. TS resolved references, construction/export and route registry inspected; callback/plugin/config/cross-process global exclusion incomplete => UNRESOLVED. Do not say entire Profile UNUSED'])
state('S-Capability','Static capability descriptions/request',['Host plugin grants + read-text registrations; model REQUEST_CAPABILITY'],['Runtime admission and host executable dispatch'],'MODEL_CHOICE/EXECUTION',True,True,False,['Default server discovery/grants empty; arbitrary builtin tools are not automatically available'])
state('S-ToolResult','Read-text ServerMcpToolResult',['readAuthorizedLocalText result transient'],['createServerMcpReadTextObservation'],'TRANSIENT_OBSERVATION',False,False,False,['64k read result not durable learned experience; normalize limit can remove all body'])
state('S-Observation','CognitionCapabilityObservation',['Binding-validated tool result normalization'],['Next Reasoning input pair'],'MODEL_INPUT',True,True,False,['16k-char overflow status hides successful read and cause'])
state('S-Effect','Intent/attempt/outcome and transient effect result',['EffectDispatcher; host adapters; provider/publication accounting'],['Claim/cancel/reconcile workers and operation freshness; adapter caller'],'RELIABILITY/CONTROL',False,True,True,['APPLIED is contract-layer completion, not proof model understood; volatile grants not restored after reboot'])
state('S-Events','Runtime events',['createEvent + EventBus.publish'],['Runtime/display/presentation/dashboard wildcard subscribers'],'CALLBACK_AND_DISPLAY','Depends on subscribed handler','Depends on subscribed handler',True,['Subscriber resolution can be dynamic; EventBus catches errors; publication receipt is not transaction over subscribers'])
state('S-Dashboard','Recent diagnostic events',['Context wildcard DashboardStateService'],['HTTP events/debug and WS dashboard'],'ADMINISTRATION_ONLY',False,False,False,['Intentional bounded diagnostics; NOT USED by model is not automatically a waste'])
state('S-Publication','Reply target/frame/publish status',['HTTP/SSE/WS outward effects'],['Transport clients; terminal reply/persistence/reconcile policy'],'EXTERNAL_EFFECT/RELIABILITY',False,True,True,['Transport delivery is not reader comprehension; full DB failure/restart requires deployed probe'])
state('S-TTSReceipt','Synthesis metadata receipt',['HostTtsReceiptAdmission'],['Media effect causal authority; Journal'],'AUTHORITY_METADATA',False,True,False,['Raw text deliberately NOT_RETAINED, no expected semantic consumer for raw receipt text'])
state('S-Media','Audio/speech segment seals/playback acknowledgments',['Media effect service; provider audio; client reports'],['Publication/playback gate and client'],'EXTERNAL_OUTPUT/CONTROL',False,True,True,['Acknowledged playback not thought/learning; all client state transitions pending'])
state('S-Speech','STT whole text + timed per-speaker segment text',['Actual local SttEngine.handle_transcribe'],['LocalSTT provider; finalized speech reservation; review; transcript context'],'INPUT_OBSERVATION',True,False,True,['Actual sidecar preserves span words; downstream transcript-only input may lose cluster distinctions'])
state('S-VoiceProfile','Acoustic template/match/binding evidence',['SpeakerStore + governed native enrollment; matching result'],['Speech attribution/review; product binding governed commands'],'PERCEPTION_AND_IDENTITY_CONTROL','Only projected evidence',True,True,['Never equate acoustic match to Person trust; full native transaction/reconcile untested'])
state('S-Supervisor','PID/ownership/health/leases',['Native supervisor + TS service supervisor'],['UI diagnostics; restart/stop/capture lease logic'],'PROCESS_RELIABILITY',False,True,True,['Platform execution not performed; no automatic individual intelligence claim'])
state('S-Settings','Runtime/product settings and secrets',['Native config commands; server settings APIs'],['env_export; ProviderRegistry/context boot; management UI'],'CONFIGURATION',False,True,False,['Configured features can still lack model entry; private deployed settings unknown'])
state('S-Dream','Recent episodes/Dream jobs',['post-turn recent episode consider/enqueue'],['runDue in post-turn path; writer only if configured'],'ASYNC_STATE_UPDATE','Only written memory when available',False,True,['No complete dynamic proof of all timer hosts; default inspected call lacks idleMs; global NO worker claim not upgraded'])
state('S-Proactive','Consent/engagement/eligibility/policy and scheduling',['Explicit controller + runtime activity + proposal'],['Runtime scheduler decision, admission, Character proactive expression'],'ACTION_SELECTION',True,True,True,['Default-session context issue reused; consent policy is necessary; exhaustive suspend/resume not closed'])
state('S-Vision','Raw image transient + analysis text',['Media/provider vision or message image attachment'],['Current turn multimodal evidence and outward perception event'],'MODEL_OBSERVATION',True,False,'Conditional text/history',['Raw media not retained; repeated observation tools not universally wired; real-device/provider quality open'])
state('S-WSTrace','WebSocket ActiveTraceRegistry',['socket message envelope -> add(traceId); admitted turn'],['EventBus output filter; outward target acceptance; terminal/close cleanup'],'TRANSPORT_SELECTION',False,True,True,['Unsupported envelope type reusing existing trace deletes pending legitimate turn; whole normal/negative/counterfactual route probe; complete durable publisher/device not tested'])
# C exact field transformations, with source span and downstream shape.
def boundary(id,traceids,stateids,path,start,end,fun,inp,outp,preserved,lost,added,condition,downstream,proof):
 out['boundaries'].append({'id':id,'traceIDs':traceids,'stateIDs':stateids,'function':fun,'inputStructure':inp,'outputStructure':outp,'preservedFields':preserved,'discardedFields':lost,'addedInterpretations':added,'conditions':condition,'downstreamConsumer':downstream,'evidence':[evidence(path,start,end)],'analysisStatus':'FIELDS_REVIEWED','proof':proof})
boundary('C-FileObservation',['A-ReadText'],['S-ToolResult','S-Observation'],'apps/server/src/mcp-read-text-observation.ts',74,134,'normalizeOutcome/extractReadTextContent','INVOKED {result:{isError:false,content:[{type:"text",text}]}}','{version,capabilityRef,status,content?}',['text blocks joined with newline when <=16000; opaque ref'],['path/tool name/runtime rejection reason; all content when >16000 or malformed'],['Successful local read reclassified ERROR if contract validation throws'],'UTF-16 string length >16000 even if reader accepted <=64000 bytes','Next Reasoning request observation pair','S + P backend-results.json readText')
boundary('C-WSQuery',['A-WS'],['S-Dashboard'],'apps/server/src/routes/websocket.ts',96,145,'WebSocketQuerySchema.safeParse/dashboard branch','query {dashboard?:unknown}','boolean dashboardMode + target predicate',['default absent false; literal boolean false false'],['string spelling false semantics'],['z.coerce.boolean("false") => true'],'Nonempty query string including false','Wildcard event stream and accounted target gate','S + P backend-results.json websocket')
boundary('C-Dashboard',['A-WS','A-Dashboard'],['S-Events','S-Dashboard'],'apps/server/src/services/dashboard.ts',19,62,'redactValue','RuntimeEvent.payload object','same object shape with sensitive-key values [redacted]',['ordinary content/text, nested nonsensitive fields'],['apiKey/token/secret/password values; URL userinfo'],['key-name redaction not scope filter'],'Dashboard mode forwards every wildcard event','Socket/dashboard API','S + P foreign-session marker retained')
boundary('C-TTSWire',['A-TTS'],['S-Media'],'packages/providers/src/local/DotsTTSProvider.ts',61,121,'synthesizeSpeech','TTSInput {text,metadata.language,voice,format,signal}','HTTP {requestId,text,language uppercase,voice?}; TTSOutput or ProviderError',['full text without split/truncation; explicit voice'],['local options format/signal not body; sidecar response error reason collapsed to status message'],['UUID; uppercase language; HTTP400 unknown effect-state'],'Whole text >2000 chars reaches actual sidecar and is rejected','WAV publication or provider error','S + real localhost cross-language P, waveform mocked')
boundary('C-TTSReceipt',['A-TTS'],['S-TTSReceipt','S-Journal'],'apps/server/src/tts-receipt-admission.ts',65,95,'HostTtsReceiptAdmission.admit','structural {textCharacterCount,voiceSupplied,languageSupplied,format,sessionId?}','Journal summary + NOT_RETAINED/nonselectable raw text descriptor',['counts/options presence and admitted causal ref'],['raw synthesis text and option values from this seam'],['CONTROL receipt with principal/source unresolved'],'Every standalone TTS admission','Media causal validation, not semantic memory','S intentional privacy boundary')
boundary('C-STTSpans',['A-STT'],['S-Speech'],'services/local-stt/server.py',335,375,'SttEngine.handle_transcribe','decoded waveform; diarize/identify flags','{text,language,identity,voiceProfileMatch,segments:[{startMs,endMs,speakerClusterId,text}],latencyMs,device}',['timing/clusters; span-specific text; whole transcript separately'],['raw waveform; no default ASR confidence field produced'],['Each span independently transcribed when >1 span'],'Diarize yields spans; identify separately gated','TS provider and speech admission','S + P python-results.json STT')
boundary('C-NativeEnv',['A-Native'],['S-Settings'],'apps/desktop/src-tauri/src/config/env_export.rs',160,210,'public_env_overrides/secret_env_overrides/combined_env_for_supervisor','Settings + secret store + managed/external mode','child env map',['selected provider config and applicable owned secrets'],['unowned consumer secrets not forwarded'],['explicit DATABASE_URL/keys only for selected managed consumers'],'managed memory/provider consumer chosen','Owned Runtime/Mem0 process','S; platform execution not tested')
boundary('C-WSTrace',['A-WS'],['S-WSTrace','S-Publication'],'apps/server/src/routes/websocket.ts',162,251,'registerWebSocketRoutes','existing active trace T + new client RuntimeEvent {traceId:T,type:not-user.message}','error frame + removed T; later valid reply filtered out',['original admitted Runtime turn continues; rejection message'],['pre-existing activeTrace ownership and subsequent valid reply visibility'],['packet rejection cleans shared trace even when traceAlreadyActive true'],'unsupported type, or outer payload parse failure; tested unsupported type while valid turn pending','Normal WS event filter and target predicate','S + P backend-results pendingReply; host receipt/Runtime event producer injected; deletion guard is runtime-only counterfactual')
# These are reviewed/reused production seams; pointers intentionally targeted, not broad full-file claims.
for id,ts,ss,p,a,b,f,i,o,keep,drop,add,cond,consumer,proof in [
('C-Receipt',['A-HTTP','A-SSE'],['S-Journal'],'apps/server/src/conversational-receipt-admission.ts',95,142,'admit','normalized text + session + transport identity hints','text payload + ATTRIBUTED_ASSERTION receipt',['text Unicode-codepoint range; explicit image-presence descriptor'],['raw image retention; authenticated principal absent'],['authority principal UNRESOLVED'],'Journal configured/valid host append','Runtime/finalized ingestion','S targeted'),
('C-Context',['A-HTTP','A-SSE'],['S-Context'],'packages/character-harness/src/assembly-v2d.ts',37,77,'assembleCharacterHarness2DContext','ordered ABI section list + budgets','included prefix + omittedSectionKinds',['whole included sections; cognition evidence/uncertainty when selected'],['oversized first failed section and all later ones'],['budgetClosed true no backfill'],'next section exceeds maxSemanticCharacters or maxSections','Character ABI render','S; previous P reused, no quality M'),
('C-Control',['A-HTTP'],['S-Context','S-Capability'],'apps/server/src/character-runtime.ts',139,262,'createServerCharacterPort/generateInitialCharacterTurn/generatePostCognitionCharacterTurn','assembled context/current input','control output then expression result',['authored constraints/provider parameter routing'],['open-ended free answer is subject to control parser'],['explicit RESPOND/SILENCE/NEED_COGNITION decision'],'Character port active','Runtime control decision and possible Cognition','Current SHA hash-verified previous control probes; full branch matrix pending'),
('C-Publication',['A-HTTP','A-SSE'],['S-Publication','S-Conversation'],'apps/server/src/routes/message.ts',198,231,'handleMessage','Runtime AgentReplyEvent|null','accounted response or {reply:null,...}',['final reply content when present; trace'],['null has no assistant message'],['null treated intentional success'],'Character silence/termination','HTTP user and conversation persistence','S targeted; no model-quality inference'),
('C-CapabilityRequest',['A-ReadText'],['S-Capability'],'apps/server/src/mcp-capability-binding.ts',467,490,'bindServerMcpCapabilityRequest','opaque capabilityRef/request + host-issued registry','implementationRef/toolName/request',['semantic request'],['no arbitrary concrete tool name granting'],['binding resolves only admitted descriptor'],'Issued registry binding exists','Host executable dispatcher','S targeted; complete plugin dynamic loading pending'),
('C-Mem0',['A-Mem0','A-HTTP'],['S-Mem0'],'packages/core/src/runtime-orchestrator.ts',5820,5845,'retrieveMemoriesForQuery','configured MemoryProvider search response','selected semantic memory context',['Mem0 record text marker in actual model input (prior P)'],['retrieval omissions/caps depend query and backend'],['backend-specific source evidence'],'MEMORY_BACKEND=mem0 or shadow path','Character/Reasoning context','Prior recorder probe/source hashes reused; live Python inference not run'),
('C-SpeechContext',['A-STT'],['S-Speech','S-Conversation'],'packages/core/src/runtime-orchestrator.ts',1528,1590,'commitSpeechTurn','finalized observation with timed segments','UserMessageEvent + later transcript input',['whole text; committed timed segments'],['prior P: segment confidences not committed; cluster IDs absent from Character request'],['voice-source event normalization'],'speech reservation/finalization passes','Conversation and Character input','Prior P with custom-capable provider fields; local STT does NOT supply confidence by default')]:boundary(id,ts,ss,p,a,b,f,i,o,keep,drop,add,cond,consumer,proof)
for id,kind,p,reason in [
('OPEN-PROFILE-DYNAMIC','DYNAMIC_CONSUMER_SCOPE','packages/memory/src/profile-lifecycle.ts','A4 explicit NOT_USED is confirmed; global facade/host callback/plugin/config consumer exclusion not complete. No NO_PRODUCTION_CONSUMER declaration.'),
('OPEN-PLATFORM-RUST','PLATFORM_TOOL_GAP','apps/desktop/src-tauri/src/supervisor.rs','One tree-sitter ERROR; no cargo/rustc/pwsh, platform-conditioned native/service launch and packaging not executed.'),
('OPEN-BRANCHES','BRANCH_ACTIVITY_UNCONFIRMED',None,'All remote heads enumerated and compared; commit dates/open PRs cannot establish actual maintenance/deployment; non-QQ variant functions not exhaustively read.'),
('OPEN-PLUNGE','BRANCH_DEEP_REVIEW_GAP',None,'Independent QQ inventory locked to adff0c...; branch AST and all callbacks are not deeply audited in this round; old branch probes only bounded reuse.'),
('OPEN-MODEL','REAL_MODEL_EVIDENCE_GAP',None,'No same-model quality comparison or live credential/device tests. Deterministic control probes cannot measure actual Alice intelligence.'),
('OPEN-DB','PROCESS_RUNTIME_RECOVERY_GAP',None,'No real PostgreSQL recovery/fence/cancel/reconcile integration run this round.'),
('OPEN-CONFIG-PRESENTATION','DYNAMIC_PLATFORM_CONFIG_GAP',None,'PowerShell/Batch/YAML/CSS/GLSL/assets metadata only; actual release/platform selection or graphics consumers not fully traced.'),
('OPEN-UNTYPED-STATES','DYNAMIC_STATE_DISCOVERY_GAP',None,'All TS type/interface/class declarations are now retained in B, not selected by familiar state words. Untyped caches, closures and runtime-computed semantic objects still require producer/write-site investigation; declaration coverage is not an exhaustive semantic-state universe.'),
('OPEN-ALL-PATHS','BEHAVIOR_PATH_GAP',None,'Positive/negative/counterfactual cases cover selected high-risk seams; remaining entry/state/transform candidates retain individual OPEN_GAPs.')]:out['gaps'].append({'id':id,'kind':kind,'path':p,'status':'OPEN_GAP','reason':reason})
import re
for t in out['traces']:
 for step in t['steps']:
  body=(root/step['path']).read_text();tokens=[re.sub(r'^new\s+','',v.strip()) for v in step['function'].split('/')];step['symbolReferences']=[]
  for token in tokens:
   match=re.search(r'\b'+re.escape(token)+r'\b',body)
   assert match is not None, f'Nonexistent trace symbol {step["path"]}:{token}'
   step['symbolReferences'].append({'identifier':token,'firstReferenceLine':body[:match.start()].count('\n')+1,'validation':'IDENTIFIER_EXISTS_IN_PINNED_SOURCE_NOT_CALL_REACHABILITY_PROOF'})
(here/'manual-review.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
print(json.dumps({k:len(out[k]) for k in ['files','traces','states','boundaries','gaps']}))
