"""Explicit probe boundaries + scenario-to-graph checks; no synthesized quality scores."""
import json,hashlib,subprocess
from pathlib import Path
import sys
p=Path(__file__).resolve().parent;root=Path(sys.argv[1]);sha=json.load(open(p/'source-inventory.json'))['baselineSHA']
old='46a24878536d537021c49d50c5ce004d93489628'
changed=subprocess.check_output(['git','-C',str(root),'diff','--name-only',old,sha,'--','apps','packages','services','scripts'],text=True).splitlines();assert not changed
prior=[root/'docs/research/backend-intelligence-value/experiments/backend-results.json',root/'docs/research/production-intelligence-loss/experiments/main-results.json']
reuse={'baselineSHA':sha,'comparisonBaseline':old,'changedProductPaths':changed,'reuseCondition':'Git two-tree product paths byte-identical, not assumption based on docs-only title','artifacts':[{'gitPath':str(x.relative_to(root)),'sha256':hashlib.sha256(x.read_bytes()).hexdigest(),'actualModelQualityEvidence':False} for x in prior],'limits':'Previous probes have their own injected-provider/evidence dependencies; current hashes permit bounded reuse, not expanded claims. No previous report is used to close all current consumer gaps.'}
(p/'prior-evidence-reuse.json').write_text(json.dumps(reuse,indent=2)+'\n')
rows=[
('pending-WS-reply','experiments/backend-results.json#pendingReply','Valid receipt/admitted input and scoped eventual reply delivered','Unsupported packet reuses existing trace while turn pending; eventual reply produced but not delivered','Same packet/turn/event, guard deletion of pre-existing trace during invalid-packet handling restores delivery','Actual WS handler/schema/ActiveTraceRegistry/EventBus; Journal receipt and Runtime event producer injected; no durable output or quality claim'),
('authorized-text','experiments/backend-results.json#readText','16000-char successful local read reaches next real production Reasoning input','16001/64000-char accepted file loses whole body and becomes ERROR; aborted real reader returns none','Bypass only normalizer: full admitted raw text still exists; no quality result','Actual Cognition+normalizer+filesystem; durable grant adapter/Reasoning recorder injected'),
('websocket','experiments/backend-results.json#websocket','Default/no trace suppresses foreign reply; explicit true dashboard receives it','String false receives foreign text while boolean false does not','Same event/query intent, actual boolean false suppresses foreign event','Actual route and EventBus; socket/HTTP context injected; deployment/output DB not tested'),
('character','experiments/backend-results.json#character','RESPOND/SILENCE/NEED_COGNITION represented correctly; post-cognition answer/uncertainty/caveat enters input','Already aborted produces zero Chat calls','Direct free reply has no control grammar; not tested as quality comparator','Actual port, not complete Runtime body/publication; invalid-JSON/retry/timeouts remain pending'),
('local-STT','experiments/python-results.json#stt','Actual span handler independently recognizes two spans; no-diarize normal whole transcript','Invalid WAV rejected before inference','Whole-transcript-only would lose span-specific text; actual STT preserves it','ASR/diarizer/import stub; no acoustic quality/enrollment/native command recovery'),
('dots-TTS','experiments/backend-results.json#localTTS; experiments/python-results.json#dotsTTS','Actual TS provider -> actual Python HTTP handler accepts 2000 chars, WAV transport works','2001 chars returns 400 UNSUPPORTED_INPUT; explicit service cancel returns 409','1001+1000 requests both accepted; adds a call, no quality/latency benefit proved','Waveform/GPU replaced; durable media seal and complete Runtime voice not exercised'),
('memory','prior-evidence-reuse.json','Prior real Runtime search recorder sees Mem0 marker','Prior negated forget fixture deletes matching item; failed forget becomes notFound','Faithful authorized memory text can enter context; natural correction/write+re-read still OPEN','Recorders/rule fixtures, no actual sidecar model learning'),
('relationship','prior-evidence-reuse.json','Explicit supplied interpretation can be projected to P8 context','Empty candidate has no relationship meaning despite evidence','Add valid interpretation marker changes projection, not proof it is true','No autonomous relationship generation quality'),
('proactive','prior-evidence-reuse.json','Authorized ordinary work-session turn receives work context','Default proactive decision reads different default-session context','Same session selection would make work history available; quality unknown','Real scheduler executor fixture; all consent/engagement/resume paths incomplete'),
('dream','prior-evidence-reuse.json','Explicit elapsed idle input can trigger; enqueue due job state visible','Current caller shape lacks idleMs; queued job alone never executes','Supply elapsed input changes trigger opportunity, not semantic consolidation quality','Real engine/in-memory state; actual DB worker/crossprocess clocks not run'),
('reply-control','prior-evidence-reuse.json','Prior ordinary RESPOND leads to accepted body recorder','Prior length finish throws control error; repeated CONTINUE consumes no new evidence','Delivering original body/adding observation avoids that exact input gap; no model-quality proof','Control/output paths only; no broad deletion recommendation'),
('affect','prior-evidence-reuse.json','Original user text remains in request','Negated worry still adds anxious hint','Remove wrong hint while keeping original text yields less contradictory input','Quality gain requires same-model M')]
coverage={'baselineSHA':sha,'actualModelQualityExperiments':0,'probeGroups':[{'capability':name,'evidence':ev,'positive':pos,'negative':neg,'counterfactual':cf,'boundary':bd,'evidenceType':'DETERMINISTIC_OR_HASH_VERIFIED_REUSE','effectiveQuality':'UNTESTED'} for name,ev,pos,neg,cf,bd in rows],'uncoveredHighRiskPaths':['All HTTP/media failures and retry combos','Natural-language correction -> durable write -> later recall','Real Profile/People dynamic readers','Plugin load callbacks timeout/cancel recovery','SQL effect outbox/fence/reconcile restart','Native voice enrollment/speaker/person-binding recovery','Vision/device capture and repeated observation','Browser SSE/audio/Live2D timing','Branch-specific production paths','Multiuser deployed settings and actual Alice SHA']}
(p/'behavior-coverage.json').write_text(json.dumps(coverage,ensure_ascii=False,indent=2)+'\n')
scenarios=[('日常聊天','A-HTTP','Character RESPOND/control -> body -> accounted output','部分确定性证据，真实自然度未测'),('多轮历史与跨轮修改','A-HTTP','Conversation -> canonical recent context','历史读取存在，长原文/纠正/取消组合未闭合'),('长期记住与召回','A-Mem0','grounded candidate -> backend -> search -> model','已有召回正例；自然语言写入纠正跨重启未验证'),('人物识别','A-STT','voice profile match -> evidence/binding -> scope/P8','声学模板不等于人物理解；真实设备待测'),('纠正记忆/关系','A-HTTP','rule/correction store -> subsequent model','部分规则负例复用；自然纠正与失效路径 OPEN'),('授权文件读取','A-ReadText','host authorization -> actual read -> observation -> Reasoning','16k 正反例和信息反事实已测；普通用户授权入口不足'),('工具反馈与多步查证','A-ReadText','REQUEST_CAPABILITY -> result pair -> next reasoning','反馈消费正例；重复 CONTINUE/更多工具/长期学习未闭合'),('图像/屏幕理解','A-Vision','receipt -> Vision -> text evidence -> Character','源码候选链；真实模型/硬件未测'),('语音理解','A-STT','waveform -> span transcripts -> committed turn/context','侧车正例；下游说话者区分能力需端到端对照'),('语音输出','A-TTS','whole/segmented input -> selected provider -> playback','跨语言上限/取消已测；完整播放回执恢复未测'),('主动行为','A-Proactive','consent -> policy -> timer/provider -> admitted reply','默认会话复用负例；多轮主动体验未测'),('长期恢复','A-Worker','Journal/outbox/ingestion/profile leases -> workers','装配已查；真实 DB 重启故障未跑'),('桌面宿主','A-Native','Tauri settings/services/native commands','Rust AST+针对阅读；平台与发布缺口'),('WebUI与Dashboard','A-Browser','browser input/HTTP-SSE-WS/presentation/diagnostics','入口/诊断查过；UI 全交互时序未审完'),('QQ/Plunge',None,'adff0c standalone plugin/surface transport','独立清单/语法索引与旧分支探针；不混入 main'),('隐私诊断流','A-WS','dashboard query -> wildcard/redaction','false-string 扩流确定性已测；部署边界未确认')]
(p/'user-scenario-checklist.json').write_text(json.dumps({'baselineSHA':sha,'scenarios':[{'scenario':s,'traceID':t,'expectedChain':c,'status':status} for s,t,c,status in scenarios],'inverseCheck':'Backend states with no matching user scenario are not automatically waste; management/validation/recovery are necessary. Every missing product consumer stays UNRESOLVED.'},ensure_ascii=False,indent=2)+'\n')
